# Generated by Django 4.0.6 on 2022-08-15 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterstellarObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nazwa')),
                ('type', models.CharField(max_length=128, verbose_name='Typ')),
                ('constellation', models.CharField(max_length=256, verbose_name='Gwiazdozbiór')),
                ('distance', models.CharField(max_length=128, verbose_name='Odległość (ly)')),
                ('apparent_magnitude', models.FloatField(verbose_name='Jasność (mag)')),
                ('size', models.CharField(max_length=128, verbose_name='Rozmiar')),
                ('messier_catalogue', models.CharField(blank=True, max_length=16, null=True, verbose_name='Katalog Messiera')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='MoonObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('diameter', models.BigIntegerField(verbose_name='Średnica (km)')),
                ('apoapsis', models.IntegerField(verbose_name='Apocentrum (km)')),
                ('periapsis', models.IntegerField(verbose_name='Perycentrum (km)')),
                ('orbital_period', models.FloatField(verbose_name='Okres orbitalny (d)')),
                ('orbital_speed', models.FloatField(verbose_name='Prędkość orbitalna (km/s)')),
                ('rotation_period', models.CharField(max_length=128, verbose_name='Okres obrotu (h)')),
                ('apparent_magnitude', models.FloatField(verbose_name='Jasność (mag)')),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystemObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('radius', models.BigIntegerField(verbose_name='Promień (km)')),
                ('aphelion', models.FloatField(verbose_name='Aphelium (au)')),
                ('perihelion', models.FloatField(verbose_name='Peryhelium (au)')),
                ('orbital_period', models.FloatField(verbose_name='Okres orbitalny (d)')),
                ('orbital_speed', models.FloatField(verbose_name='Prędkość orbitalna (km/s)')),
                ('rotation_period', models.FloatField(verbose_name='Okres obrotu (h)')),
                ('apparent_magnitude', models.FloatField(verbose_name='Jasność (mag)')),
                ('natural_satellites', models.IntegerField(verbose_name='Liczba naturalnych satelitów')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interstellar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interstellar_app.interstellarobject')),
                ('moon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interstellar_app.moonobject')),
                ('solar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interstellar_app.solarsystemobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='moonobject',
            name='satellite_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interstellar_app.solarsystemobject'),
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interstellar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interstellar_app.interstellarobject')),
                ('moon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interstellar_app.moonobject')),
                ('solar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interstellar_app.solarsystemobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
